/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package adventofcode;

import java.io.FileNotFoundException;

public class App {
  public static void main(String[] args) throws FileNotFoundException {
    Stage2.score("D:\\AdventOfCode\\app\\src\\main\\resources\\input2.txt");
    Stage3.score("D:\\AdventOfCode\\app\\src\\main\\resources\\input3.txt");
  }
}
