/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package adventofcode;

import java.io.FileNotFoundException;

public class App {
  public static void main(String[] args) throws FileNotFoundException {
  }
}
